# sops configuration file
# See: https://github.com/getsops/sops#using-sops-yaml-conf-to-select-kms-pgp-for-new-files

keys:
  # Add your age public key here (get it from: age-keygen -y ~/.config/sops/age/keys.txt)
  - &user age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  # Encrypt secrets/*.yaml files with age
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *user
